<?php
	define("BILL_STATUS_BILLED",1);
	define("BILL_STATUS_PAID", 2);
	define("BILL_STATUS_CANCELLED", 3);
	define("BILL_STATUS_BOOKED", 4);
	define("BILL_STATUS_HOLD", 5);

	define("BILL_KITCHEN_STATUS_TO_KITCHEN",1);
	define("BILL_KITCHEN_STATUS_ACCEPT", 2);
	define("BILL_KITCHEN_STATUS_REJECT", 3);
	define("BILL_KITCHEN_STATUS_FINISHED", 4);
	
?>
