// 13-JAN-2014
ALTER TABLE `bills` ADD `sync` BOOLEAN NOT NULL DEFAULT '0',  ADD `sync_id` INT NULL;
ALTER TABLE `bill_items` ADD `sync` BOOLEAN NOT NULL DEFAULT '0',  ADD `sync_id` INT NULL;
ALTER TABLE `counter_items` ADD `sync` BOOLEAN NOT NULL DEFAULT '0',  ADD `sync_id` INT NULL;
